### ISSUE TITLE
ERROR: A failure occured in build() aborting.

### ISSUE THREAD

**Issue by StarrKiss** [bartoszek/AUR-blender-2.8-git#3]
ninja: build stopped: subcommand failed.
metric                  count   avg (us)        total (ms)
.ninja parse            2       21320.5         42.6
canonicalize str        24391   0.1             2.4
canonicalize path       87949   0.1             8.2
lookup node             87949   0.3             24.5
.ninja_log load         1       14.0            0.0
.ninja_deps load        1       2.0             0.0
node stat               9721    1.3             12.4
StartEdge               234     10026.0         2346.1
FinishCommand           234     1065.5          249.3

path->node hash load 0.90 (13616 entries / 15173 buckets)

Other error messages on yay -S blender-2.8-git.

**Comment by bartoszek** [comment]
I've included some control variables which can be used to tweak the build process.
* `DISABLE_CUDA` to skip cycles and compositor cuda kernels
* `DISABLE_NINJA` to swich build system from ninja to make
* `TRAVIS` to limit cuda arch>=5.0

You can invoke them like this:
```sh
DISABLE_NINJA=1 yay -S blender-2.8-git
```

For me it looks like memory issue when building sm_3x kernels, have the same issue on `travis ci` worker (3GB_ram+1.5GB_swap) with `blender-2.7` package. Try `TRAVIS=1 yay -S blender-2.8-git` first :thinking:

**Comment by StarrKiss** [comment]
Thats odd, it cant be amemory issue because I have 16 gigs of ram

**Comment by bartoszek** [comment]
Keep in mind that `nvcc` is build in `compile_pool` witch uses `nproc`+2 jobs. And `ptxas` is quite greedy, especially for sm_3x.
```
  PID User     Command                         Swap      USS      PSS      RSS 
... 
20470 bartus   ptxas -arch sm_50 -m64 -v /     1.0M     1.1G     1.1G     1.1G 
20477 bartus   ptxas -arch sm_75 -m64 -v /     1.0M     1.2G     1.2G     1.2G 
20639 bartus   ptxas -arch sm_61 -m64 -v /     1.0M     1.3G     1.3G     1.3G 
20550 bartus   ptxas -arch sm_52 -m64 -v /     1.0M     1.4G     1.4G     1.4G 
20504 bartus   ptxas -arch sm_60 -m64 -v /     1.0M     1.4G     1.4G     1.4G 
20528 bartus   ptxas -arch sm_70 -m64 -v /     1.0M     1.4G     1.4G     1.4G
23110 bartus   ptxas -arch sm_30 -m64 -v /    23.9M     3.0G     3.0G     3.0G 
23237 bartus   ptxas -arch sm_35 -m64 -v /     6.0M     3.0G     3.0G     3.0G 
```

**Comment by bartoszek** [comment]
I've made some polish to `SelectCudaComputeArch`. Now it should work fine without nvidia card present.
I've tested it on `Travis`, could you gave me your impression (run `yay -S blender-2.8-git` without any env vars)...

**Comment by Fweeb** [comment]
Just tried building today. It seems that DISABLE_NINJA doesn't quite fully disable ninja. Cmake completes the compile process, but it fails at linking with:

```
ninja: error: loading 'build.ninja': No such file or directory
```

**Comment by bartoszek** [comment]
@Fweeb Can't reproduce: gave me more detail of your build rutine (aur helper if any)
Here it buildd just fine with `yay||aurutils` in `arch-nspawn`.

Behavior differs between the aur helpers. `yay` for example has static deps resolution wiht `aur rcp`, where `aurutils` source `PKGBUILD` allowing env vars to influence dependencies. But they all finally call `makepkg` ergo their behavior during `build()` should be the same :thinking:

**Comment by Fweeb** [comment]
@bartoszek As it turns out, I didn't realize that I hadn't done a proper system update on that machine in a while. A quick `pacman -Syu` and everything turned out fine. My apologies for the noise.
