### ISSUE TITLE
No denoise node in compositor with oidn installed

### ISSUE THREAD

**Issue by bda65** [bartoszek/AUR-blender-2.8-git#6]
Hi,
I've installed  oidn (from AUR). I've tried to add -DWITH_OPENIMAGEDENOISE=ON to the PKGBUILD without success.
Blender is linked to libOpenImageDenoiser but there's no denoise node in the compositor.

Can you add it, please?

**Comment by bartoszek** [comment]
`WITH_OPENIMAGEDENOISE=ON` is set in [blender_release.config](https://developer.blender.org/diffusion/B/browse/master/build_files/cmake/config/blender_release.cmake$44) which is sourced in [PKGBUILD:build()](https://github.com/bartoszek/AUR-blender-2.8-git/blob/master/PKGBUILD#L85) it's redundant to add extra `-DWITH_OPENIMAGEDENOISE=ON` to the `PKGBUILD`
I've rebuild `blender-2.8-git` just now, and `Denoise` node is present in `compositor`
![Screenshot_2019-10-11_20-25-31](https://user-images.githubusercontent.com/1213348/66675353-762ca480-ec65-11e9-802a-741d209887fa.png)

**Comment by bda65** [comment]
It disappeared at the same time as  the new Nvidia OptiX option.
No denoise node:
![2019-10-12-092206_2560x1440_scrot](https://user-images.githubusercontent.com/45999955/66697167-ad7d6e80-ecc2-11e9-9bc3-a6a4c138d9a5.png)
![2019-10-12-092328_2560x1440_scrot](https://user-images.githubusercontent.com/45999955/66697174-bf5f1180-ecc2-11e9-89e3-305967376607.png)

> ldd /usr/bin/blender-2.8 | grep OpenImage
>         libOpenImageIO.so.2.0 => /usr/lib/libOpenImageIO.so.2.0 (0x00007fde6ea67000)
> 	libOpenImageDenoise.so.0 => /usr/lib/libOpenImageDenoise.so.0  (0x00007fde6c171000)

>ls -l /usr/lib/libOpenImageDenoise.so*
>lrwxrwxrwx 1 root root       24 11 oct.  16:30 /usr/lib/libOpenImageDenoise.so -> libOpenImageDenoise.so.0
>lrwxrwxrwx 1 root root       28 11 oct.  16:30 /usr/lib/libOpenImageDenoise.so.0 -> >libOpenImageDenoise.so.1.0.0
>-rwxr-xr-x 1 root root 37466216 11 oct.  16:30 /usr/lib/libOpenImageDenoise.so.1.0.0`

I do not know why the oidn is linked as libOpenImageDenoise.so.0. Problem may be here...
I'll try to reinstall from fresh download of oidn and your AUR package now.

Thanks for your help.

**Comment by bda65** [comment]
Removed optix, blender-2.8-git and oidn.
New, fresh compilation of oidn and blender-2.8-git resolved the problem.
I don't know what's happened here.
So sorry...
